# Generated by Django 3.1.3 on 2020-11-13 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('item_name', models.CharField(max_length=200)),
                ('item_price', models.IntegerField()),
                ('item_type', models.CharField(choices=[('car', 'Car'), ('house', 'House')], max_length=200)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.itempost')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_addr', models.CharField(max_length=200)),
                ('item_post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.itempost')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField(max_length=200)),
                ('bank_loan', models.CharField(max_length=200)),
                ('bed_unit', models.IntegerField()),
                ('item_post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.itempost')),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=200)),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=200)),
                ('manu_year', models.DateField()),
                ('engine_type', models.CharField(choices=[('diesel', 'Diesel'), ('benzine', 'Benzine')], max_length=200)),
                ('car_condition', models.CharField(choices=[('new', 'New'), ('sl_used', 'Slightly Used'), ('used', 'Used')], max_length=200)),
                ('drive_type', models.CharField(choices=[('two_wheel', '2 Wheel Drive'), ('four_wheel', '4 Wheel Drive')], max_length=200)),
                ('car_color', models.CharField(max_length=200)),
                ('mileage', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('item_post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.itempost')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('car', 'Car'), ('house', 'House')], max_length=200)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
