# Generated by Django 3.1.3 on 2020-11-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_verified',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_num',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
