# Generated by Django 3.1.3 on 2020-11-30 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20201126_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_num',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_color',
            field=models.CharField(blank=True, choices=[('old', "It's own color"), ('New', 'Color renewed')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('sl_used', 'Slightly Used'), ('used', 'Used')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_model',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='drive_type',
            field=models.CharField(blank=True, choices=[('two_wheel', '2 Wheel Drive'), ('four_wheel', '4 Wheel Drive')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='engine_type',
            field=models.CharField(blank=True, choices=[('diesel', 'Diesel'), ('benzine', 'Benzine')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='item_post_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.itempost'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='manu_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='mileage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='transmission',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='area',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='bank_loan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='bed_unit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
