# Generated by Django 3.1.3 on 2020-12-01 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20201130_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='description',
            new_name='car_description',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='description',
            new_name='house_description',
        ),
    ]
