# Generated by Django 3.1.3 on 2020-12-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20201201_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_color',
            field=models.CharField(choices=[('old', "It's own color"), ('New', 'Color renewed')], default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_condition',
            field=models.CharField(choices=[('new', 'New'), ('sl_used', 'Slightly Used'), ('used', 'Used')], default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_model',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cars',
            name='mileage',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='bank_loan',
            field=models.CharField(blank=True, choices=[('free', 'Free'), ('depted', 'Depted')], max_length=200, null=True),
        ),
    ]
