# Generated by Django 3.1.3 on 2020-12-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20201201_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempost',
            name='item_type',
            field=models.CharField(blank=True, choices=[('car', 'Car'), ('house', 'House')], max_length=200, null=True),
        ),
    ]
