# Generated by Django 3.1.3 on 2020-12-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='longt',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=14, null=True),
        ),
    ]
