# Generated by Django 3.1.3 on 2020-12-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_auto_20201208_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_type',
            field=models.CharField(choices=[('broker', 'Broker'), ('company', 'Company')], default='customer', max_length=20, null=True),
        ),
    ]
