# Generated by Django 3.1.3 on 2020-12-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempost',
            name='serviceType',
            field=models.CharField(blank=True, choices=[('rent', 'Rent'), ('sell', 'Sell')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='path_addr',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
